sudo: required
dist: trusty
language: generic

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt56-trusty
  - sudo apt-get update
  - sudo apt-get -y install qt56declarative qt56quickcontrols qt56graphicaleffects qt56tools qt56svg

script:
  - qmake . && make && sudo make install