sudo: required
dist: trusty
language: generic

install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq
  - sudo apt-get -y install qt55[QTPACKAGE]

script:
  - qmake . && make && sudo make install
