sudo: required
dist: trusty
language: c++

install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
  - sudo apt-get update -qq
  - sudo apt-get -y install qt57[QTPACKAGE]

script:
  - source /opt/qt57/bin/qt57-env.sh
  - /opt/qt57/bin/qmake
  - make
  - sudo make install
